Declare main outside of extern "C" block
The C++ standard doesn't allow a linkage-specification for main,
https://eel.is/c++draft/basic.start.main#3.sentence-5:

"The main function shall not be declared with a linkage-specification
([dcl.link])."

Clang has started warning on this usage:

bionic/libc/bionic/libc_init_common.h:49:12: error: 'main' should not be 'extern "C"' [-Werror,-Wmain]
   49 | extern int main(int argc, char** argv, char** env);

Clang knows that ::main is special and won't mangle its name.

Bug: http://b/379133546
Test: treehugger
Change-Id: Id5c1092c4fcb2548469e44165874d5ca19fbce81

(cherry picked from commit dfc3a97bc3dbbbb9c85e36d2c708287c347cb873)